
name: Build JAR
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action 1 \- Checkout
        uses: actions/checkout@v3

      - name: Action 2 \- Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Action 3 \- Build with Maven
        run: mvn package -DbuildNumber=${{ github.run_number }}

      - name: Action 4 \- Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-jar-${{ github.run_number }}
          path: target/WorldResetPlugin_*.jar